### ISSUE TITLE
Page Count

### ISSUE THREAD

**Issue by th3r00t** [th3r00t/pyShelf#3]
Figure out how to get page count from epub. I am unsure as to if this is a standard count, or if it would be different depending on device.

More research is needed

**Comment by Fireblend** [comment]
See: https://stackoverflow.com/a/40561575

**Comment by th3r00t** [comment]
Thanks for the link I think this may be exactly what I was looking for!
Already having access to the individual pages i scrape the contents and do the division to return a generalized representation of pages.

**Comment by th3r00t** [comment]
For the time being im going to let page count be handled by the reader exclusively
