### ISSUE TITLE
Incorrect Website

### ISSUE THREAD

**Issue by AGIsmail** [th3r00t/pyShelf#34]
Hey,

It seems like the [pyShelf website](pyshelf.com) redirects to the below URI and renders an unrelated website for "Soulwich: Asian sandwiches & more".

URI: `http://162.255.85.132/?SID=rt6t135fm9bknvaptrrh6bf0dm`

![soulwich](https://user-images.githubusercontent.com/11680600/76333710-6246a680-62c8-11ea-9fd2-7b70aa7d8959.png)

**Comment by th3r00t** [comment]
Thanks for reminding me of this I have been in the middle of an infrastructure change with my domain names and hosting provider, I am having the domain transfered over now and should have the site back up in a day or so!

**Comment by th3r00t** [comment]
![Saturday-Mar-21-2020-18:07:32](https://user-images.githubusercontent.com/5428538/77238000-2a324400-6ba3-11ea-93f4-8007ba588732.png)

**Comment by th3r00t** [comment]
This can be closed the new sight design has been deployed
