### ISSUE TITLE
Linux Install importBooks Issue

### ISSUE THREAD

**Issue by dk850** [th3r00t/pyShelf#41]
The hashbang at the top of the importBooks file is currently just `#!python`
![image](https://user-images.githubusercontent.com/46713826/82128717-095a2980-97b5-11ea-89ed-7c3578bd9130.png)

This doesn't play well with most linux systems as it expects a full path. Should be changed to something along the lines of `#!/usr/bin/python` so it looks like this and executes correctly.
![image](https://user-images.githubusercontent.com/46713826/82128658-acf70a00-97b4-11ea-9de2-af454bc06e7c.png)

See: [This stackoverflow question](https://stackoverflow.com/questions/16757349/bad-interpreter-no-such-file-or-directory-in-python)

**Comment by th3r00t** [comment]
I believe I did this as part of debugging, and forgot to change it back. You can make a pull request, or I will update this for the next release cycle. Thanks!

**Comment by MartenBE** [comment]
If you update this, it is best to use `#!/usr/bin/env python` [1]

[1] https://askubuntu.com/questions/716280/why-do-some-python-scripts-begin-with-usr-bin-env-python

**Comment by th3r00t** [comment]
Thanks for this issue, I can confirm it has been fixed in development
